### ISSUE TITLE
can you show us the output for every file

### ISSUE THREAD

**Issue by azabcodes** [Wayaer/flutter_waya#4]

**Comment by Wayaer** [comment]
What do you mean?
If you want to know what components are available, you can run example，Or check out the readme, there is a web of the example

**Comment by azabcodes** [comment]
I find example but now when anyone wants to take any part of code it is difficult because every file depends on another one

**Comment by Wayaer** [comment]
There are a lot of core components and code in this package, and only some components are independent of the core package,So if you need separate components, you need to find the code that depends on them
